version: "2"

linters:
  enable:
    - gocritic
    - prealloc
    - perfsprint
    - bodyclose
    - makezero
    - unconvert
    - wastedassign
  settings:
    gocritic:
      enabled-checks:
        - hugeParam
        - rangeValCopy
        - appendCombine
        - indexAlloc
    govet:
      enable:
        - fieldalignment

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
